### PR TITLE
Fix #183: Show bundled elements/behaviors if needed

### LINKED ISSUE #183: iron-overlay-behavior shows iron-overlay-backdrop
https://elements.polymer-project.org/elements/iron-overlay-behavior

The above link will display `iron-overlay-backdrop` and the element page doesn't provide link to `iron-overlay-behavior`.

### PR DESCRIPTION
**Pull request by blasten**
Required: 
- [ ] https://github.com/PolymerElements/iron-component-page/pull/55

### CODE REVIEW

**Comment by shawncplus** [comment]
Just out of curiosity, was there anything wrong with https://github.com/Polymer/polymer-element-catalog/pull/184 since they're nearly identical

**Comment by blasten** [comment]
@shawncplus It was a coincidence that we were both working on the same issue. Your code looks good and does solve the issue too, but we only have two arguments. While a general solution for `N` arguments could be useful, in this case in concrete we only have two arguments

**Comment by shawncplus** [comment]
Fair enough :thumbsup:

**Comment by frankiefu** [comment]
LGTM :+1:

**Pull request merged**
