### PR TITLE
Improve perf of the layout of cards

### PR DESCRIPTION
**Pull request by blasten**
Perf optimization: https://github.com/Polymer/polymer-element-catalog/issues/199

In addition to Steve's points, I added an optimization to batch the sequence of DOM mutations. The result is really awesome. I left a comment so we can switch to dom-repeat as soon as we get this optimization for free.

Dependencies:
- [x] https://github.com/PolymerElements/iron-component-page/pull/64
- [x] https://github.com/PolymerElements/iron-doc-viewer/pull/63

Try the elements:

```
bower install PolymerElements/iron-component-page#notify-error
bower install PolymerElements/iron-doc-viewer#ui-fixes
```

cc @sorvell

### CODE REVIEW

**Comment by frankiefu** [comment]
Cards view is not showing all the elements.  For example, `Gold Elements` has 6 elements but in cards view it shows only the first 3.

screen shot 2015-10-26 at 2 02 30 pm

**Comment by frankiefu** [comment]
All the cards show have the same width but the last is too wide.

screen shot 2015-10-26 at 2 04 14 pm

**Comment by frankiefu** [comment]
On IE 11, hovering on cards doesn't show the action menu

**Comment by blasten** [comment]
I'm looking into it

**Comment by blasten** [comment]
Final result:
screen shot 2015-10-30 at 6 57 12 pm

**Comment by frankiefu** [comment]
For boolean type properties, the default value is not showing up.  For example, the `multi` property in `iron-selector`:

screen shot 2015-11-02 at 6 06 56 pm

**Comment by frankiefu** [comment]
lgtm

**Pull request merged**
