### PR TITLE
removed molecules package

### PR DESCRIPTION
**Pull request by tjsavage**

### CODE REVIEW

**Comment by tjsavage** [comment]
@blasten would you mind taking a look?

**Comment by blasten** [comment]
testing..

**Comment by blasten** [comment]
@tjsavage looks great! The only question would be what should we do with marked-element? This element is a dependency of iron-doc-viewer, should we make it an iron-marked-element?

https://github.com/PolymerElements/iron-doc-viewer/blob/master/bower.json#L25

**Comment by tjsavage** [comment]
ah good catch. Does the catalog currently support just having floating elements, not part of a top-level package?

**Comment by blasten** [comment]
Users can access to this element if they know the URL, but they won't see it in "All elements".  Also, a few links are broken. 
screen shot 2016-01-27 at 10 52 53 am

**Comment by blasten** [comment]
The molecules repo has been restored https://github.com/PolymerElements/molecules

**Comment by notwaldorf** [comment]
long live molecules!

**Pull request closed without merging**
